Drone d;
("localhost", 8081) => d.connect;
d.reset();
1::second => now;
d.takeoff();
2::second => now;
d.light("snakeGreenRed", 5, 20000);
2::second => now;
d.forward(1);
d.up(0.5);
4::second => now;
d.clockwise(0.5);
0.5::second => now;
d.stop();
d.anim("flipAhead", 500);
3::second => now;
d.anim("flipBehind", 500);
d.land();